// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dao

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Patch struct {
	ID    int32
	Name  string
	Date  time.Time
	Files json.RawMessage
}

type Quest struct {
	QuestID         int32
	LatestHistoryID int32
	Deleted         bool
}

type QuestHistory struct {
	HistoryID         int32
	PreviousHistoryID sql.NullInt32
	QuestID           int32
	FileVersion       int32
	Patch             string
	Title             sql.NullString
	Description       sql.NullString
	Summary           sql.NullString
	OldImage          sql.NullString
	IconName          sql.NullString
	NpcSpr            sql.NullString
	NpcNavi           sql.NullString
	NpcPosX           sql.NullInt32
	NpcPosY           sql.NullInt32
	RewardExp         sql.NullString
	RewardJexp        sql.NullString
	RewardItemList    sql.NullString
	CoolTimeQuest     sql.NullInt32
}
