// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dao

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type PatchesStatus string

const (
	PatchesStatusPending   PatchesStatus = "pending"
	PatchesStatusExtracted PatchesStatus = "extracted"
	PatchesStatusGone      PatchesStatus = "gone"
	PatchesStatusSkipped   PatchesStatus = "skipped"
)

func (e *PatchesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PatchesStatus(s)
	case string:
		*e = PatchesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PatchesStatus: %T", src)
	}
	return nil
}

type NullPatchesStatus struct {
	PatchesStatus PatchesStatus
	Valid         bool // Valid is true if PatchesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPatchesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PatchesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PatchesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPatchesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PatchesStatus), nil
}

type I18n struct {
	I18nID          string
	LatestHistoryID int64
	Deleted         bool
}

type I18nHistory struct {
	HistoryID         int64
	PreviousHistoryID sql.NullInt64
	I18nID            string
	FileVersion       int32
	Update            string
	ContainerFile     string
	EnText            string
	PtBrText          string
	Active            bool
}

type Item struct {
	ItemID          int32
	LatestHistoryID int32
	Deleted         bool
}

type ItemHistory struct {
	HistoryID               int32
	PreviousHistoryID       sql.NullInt32
	ItemID                  int32
	FileVersion             int32
	Update                  string
	IdentifiedDescription   sql.NullString
	IdentifiedSprite        sql.NullString
	UnidentifiedName        sql.NullString
	UnidentifiedDescription sql.NullString
	UnidentifiedSprite      sql.NullString
	SlotCount               int8
	IsBook                  bool
	CanUseBuyingStore       bool
	CardPrefix              sql.NullString
	CardIsPostfix           bool
	CardIllustration        sql.NullString
	ClassNum                sql.NullInt32
	IsCostume               bool
	EffectID                int32
	PackageID               int32
	MoveInfo                []byte
	IdentifiedName          sql.NullString
}

type LoaderController struct {
	Name           string
	LastUpdateDate time.Time
}

type Patch struct {
	ID        int32
	Name      string
	Files     json.RawMessage
	Status    PatchesStatus
	Date      time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PreviousI18nHistoryVw struct {
	HistoryID         sql.NullInt64
	PreviousHistoryID sql.NullInt64
	I18nID            sql.NullString
	FileVersion       sql.NullInt32
	Update            sql.NullString
	ContainerFile     sql.NullString
	EnText            sql.NullString
	PtBrText          sql.NullString
	Active            sql.NullBool
}

type PreviousItemHistoryVw struct {
	HistoryID               sql.NullInt32
	PreviousHistoryID       sql.NullInt32
	ItemID                  sql.NullInt32
	FileVersion             sql.NullInt32
	Update                  sql.NullString
	IdentifiedName          sql.NullString
	IdentifiedDescription   sql.NullString
	IdentifiedSprite        sql.NullString
	UnidentifiedName        sql.NullString
	UnidentifiedDescription sql.NullString
	UnidentifiedSprite      sql.NullString
	SlotCount               sql.NullInt16
	IsBook                  sql.NullBool
	CanUseBuyingStore       sql.NullBool
	CardPrefix              sql.NullString
	CardIsPostfix           sql.NullBool
	CardIllustration        sql.NullString
	ClassNum                sql.NullInt32
	IsCostume               sql.NullBool
	EffectID                sql.NullInt32
	PackageID               sql.NullInt32
	MoveInfo                []byte
}

type PreviousQuestHistoryVw struct {
	HistoryID         sql.NullInt32
	PreviousHistoryID sql.NullInt32
	QuestID           sql.NullInt32
	FileVersion       sql.NullInt32
	Update            sql.NullString
	Title             sql.NullString
	Description       sql.NullString
	Summary           sql.NullString
	OldImage          sql.NullString
	IconName          sql.NullString
	NpcSpr            sql.NullString
	NpcNavi           sql.NullString
	NpcPosX           sql.NullInt32
	NpcPosY           sql.NullInt32
	RewardExp         sql.NullString
	RewardJexp        sql.NullString
	CoolTimeQuest     sql.NullInt32
	RewardItemList    []byte
}

type Quest struct {
	QuestID         int32
	LatestHistoryID int32
	Deleted         bool
}

type QuestHistory struct {
	HistoryID         int32
	PreviousHistoryID sql.NullInt32
	QuestID           int32
	FileVersion       int32
	Update            string
	Title             sql.NullString
	Description       sql.NullString
	Summary           sql.NullString
	OldImage          sql.NullString
	IconName          sql.NullString
	NpcSpr            sql.NullString
	NpcNavi           sql.NullString
	NpcPosX           sql.NullInt32
	NpcPosY           sql.NullInt32
	RewardExp         sql.NullString
	RewardJexp        sql.NullString
	CoolTimeQuest     sql.NullInt32
	RewardItemList    []byte
}
