// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: patch-list.sql

package dao

import (
	"context"
	"encoding/json"
	"time"
)

const getLatestPatch = `-- name: GetLatestPatch :one
SELECT id, name, files, status, date, created_at, updated_at FROM ` + "`" + `patches` + "`" + ` ORDER BY ` + "`" + `id` + "`" + ` DESC LIMIT 1
`

func (q *Queries) GetLatestPatch(ctx context.Context) (Patch, error) {
	row := q.db.QueryRowContext(ctx, getLatestPatch)
	var i Patch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Files,
		&i.Status,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUpdatesCount = `-- name: GetUpdatesCount :one
SELECT COUNT(*) FROM (SELECT ` + "`" + `date` + "`" + ` FROM ` + "`" + `patches` + "`" + ` WHERE ` + "`" + `status` + "`" + ` IN ('pending', 'extracted') GROUP BY ` + "`" + `date` + "`" + `) updates
`

func (q *Queries) GetUpdatesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUpdatesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertPatch = `-- name: InsertPatch :exec
INSERT INTO ` + "`" + `patches` + "`" + ` (` + "`" + `id` + "`" + `, ` + "`" + `name` + "`" + `, ` + "`" + `date` + "`" + `, ` + "`" + `files` + "`" + `, ` + "`" + `status` + "`" + `) VALUES (?, ?, ?, ?, ?)
`

type InsertPatchParams struct {
	ID     int32
	Name   string
	Date   time.Time
	Files  json.RawMessage
	Status PatchesStatus
}

func (q *Queries) InsertPatch(ctx context.Context, arg InsertPatchParams) error {
	_, err := q.db.ExecContext(ctx, insertPatch,
		arg.ID,
		arg.Name,
		arg.Date,
		arg.Files,
		arg.Status,
	)
	return err
}

const listPatches = `-- name: ListPatches :many
SELECT id, name, files, status, date, created_at, updated_at FROM ` + "`" + `patches` + "`" + ` WHERE ` + "`" + `date` + "`" + ` <= ? AND ` + "`" + `status` + "`" + ` IN ('pending', 'extracted') ORDER BY ` + "`" + `id` + "`" + ` ASC
`

// We include pending and extracted because we may have patches marked as 'extracted' but
// that were not processed for a new record type, while gone/skipped should never be considered.
func (q *Queries) ListPatches(ctx context.Context, date time.Time) ([]Patch, error) {
	rows, err := q.db.QueryContext(ctx, listPatches, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Patch
	for rows.Next() {
		var i Patch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Files,
			&i.Status,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpdatesPatches = `-- name: ListUpdatesPatches :many
SELECT patches.id, patches.name, patches.files, patches.status, patches.date, patches.created_at, patches.updated_at
FROM (
	SELECT ` + "`" + `date` + "`" + `
	FROM ` + "`" + `patches` + "`" + `
	WHERE ` + "`" + `status` + "`" + ` IN ('pending', 'extracted')
	GROUP BY ` + "`" + `date` + "`" + `
	ORDER BY ` + "`" + `date` + "`" + ` ASC
	LIMIT ?, ?
) dates
INNER JOIN ` + "`" + `patches` + "`" + ` ON ` + "`" + `patches` + "`" + `.` + "`" + `date` + "`" + ` = dates.` + "`" + `date` + "`" + `
ORDER BY patches.` + "`" + `id` + "`" + ` ASC
`

type ListUpdatesPatchesParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) ListUpdatesPatches(ctx context.Context, arg ListUpdatesPatchesParams) ([]Patch, error) {
	rows, err := q.db.QueryContext(ctx, listUpdatesPatches, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Patch
	for rows.Next() {
		var i Patch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Files,
			&i.Status,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
