// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dao

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	CountChangedI18nsInUpdate(ctx context.Context, update string) (int64, error)
	CountChangedItemsInUpdate(ctx context.Context, update string) (int64, error)
	CountChangedMapsInUpdate(ctx context.Context, update string) (int64, error)
	CountChangedQuestsInUpdate(ctx context.Context, update string) (int64, error)
	CountI18ns(ctx context.Context) (int64, error)
	CountItems(ctx context.Context) (int64, error)
	CountMaps(ctx context.Context) (int64, error)
	CountQuests(ctx context.Context) (int64, error)
	GetChangedI18ns(ctx context.Context, arg GetChangedI18nsParams) ([]GetChangedI18nsRow, error)
	GetChangedItems(ctx context.Context, arg GetChangedItemsParams) ([]GetChangedItemsRow, error)
	GetChangedMaps(ctx context.Context, arg GetChangedMapsParams) ([]GetChangedMapsRow, error)
	GetChangedQuests(ctx context.Context, arg GetChangedQuestsParams) ([]GetChangedQuestsRow, error)
	GetCurrentI18ns(ctx context.Context) ([]GetCurrentI18nsRow, error)
	GetCurrentItems(ctx context.Context) ([]GetCurrentItemsRow, error)
	GetCurrentMaps(ctx context.Context) ([]GetCurrentMapsRow, error)
	GetCurrentQuests(ctx context.Context) ([]GetCurrentQuestsRow, error)
	GetI18nHistory(ctx context.Context, arg GetI18nHistoryParams) ([]GetI18nHistoryRow, error)
	GetI18nList(ctx context.Context, arg GetI18nListParams) ([]GetI18nListRow, error)
	GetI18nsIdsInUpdate(ctx context.Context, update string) ([]GetI18nsIdsInUpdateRow, error)
	GetItemHistory(ctx context.Context, arg GetItemHistoryParams) ([]GetItemHistoryRow, error)
	GetItemIdsInUpdate(ctx context.Context, update string) ([]GetItemIdsInUpdateRow, error)
	GetItemList(ctx context.Context, arg GetItemListParams) ([]GetItemListRow, error)
	GetLatestPatch(ctx context.Context) (Patch, error)
	GetLatestUpdate(ctx context.Context, name string) (time.Time, error)
	GetMapHistory(ctx context.Context, arg GetMapHistoryParams) ([]GetMapHistoryRow, error)
	GetMapList(ctx context.Context, arg GetMapListParams) ([]GetMapListRow, error)
	GetMapsIdsInUpdate(ctx context.Context, update string) ([]GetMapsIdsInUpdateRow, error)
	GetQuestHistory(ctx context.Context, arg GetQuestHistoryParams) ([]GetQuestHistoryRow, error)
	GetQuestList(ctx context.Context, arg GetQuestListParams) ([]GetQuestListRow, error)
	GetQuestsIdsInUpdate(ctx context.Context, update string) ([]GetQuestsIdsInUpdateRow, error)
	GetSkillJobs(ctx context.Context) ([]SkillsJob, error)
	GetStrings(ctx context.Context, ids []string) ([]GetStringsRow, error)
	GetUpdatesCount(ctx context.Context) (int64, error)
	InsertPatch(ctx context.Context, arg InsertPatchParams) error
	// We include pending and extracted because we may have patches marked as 'extracted' but
	// that were not processed for a new record type, while gone/skipped should never be considered.
	ListPatches(ctx context.Context, date time.Time) ([]Patch, error)
	ListUpdatesPatches(ctx context.Context, arg ListUpdatesPatchesParams) ([]Patch, error)
	UpsertI18n(ctx context.Context, arg UpsertI18nParams) (sql.Result, error)
	UpsertItem(ctx context.Context, arg UpsertItemParams) (sql.Result, error)
	UpsertLatestUpdate(ctx context.Context, arg UpsertLatestUpdateParams) error
	UpsertMap(ctx context.Context, arg UpsertMapParams) (sql.Result, error)
	UpsertQuest(ctx context.Context, arg UpsertQuestParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
