// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skill.sql

package dao

import (
	"context"
	"database/sql"
)

const countSkills = `-- name: CountSkills :one
SELECT COUNT(*)
FROM ` + "`" + `skills` + "`" + `
INNER JOIN ` + "`" + `skills_history` + "`" + ` ON ` + "`" + `skills` + "`" + `.` + "`" + `latest_history_id` + "`" + ` = ` + "`" + `skills_history` + "`" + `.` + "`" + `history_id` + "`" + `
WHERE ` + "`" + `skills` + "`" + `.` + "`" + `deleted` + "`" + ` = FALSE
`

func (q *Queries) CountSkills(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSkills)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCurrentSkills = `-- name: GetCurrentSkills :many
SELECT skills_history.history_id, skills_history.previous_history_id, skills_history.skill_id, skills_history.file_version, skills_history.` + "`" + `update` + "`" + `, skills_history.constant, skills_history.name, skills_history.description, skills_history.max_level, skills_history.sp_cost, skills_history.can_select_level, skills_history.attack_range, skills_history.required_skills, skills_history.job_required_skills, skills_history.skill_scale, skills_history.created_at, skills_history.ap_cost, skills_history.is_passive, skills_history.cast_flags, skills_history.cast_fixed_delay, skills_history.cast_stat_delay, skills_history.single_post_delay, skills_history.global_post_delay, ` + "`" + `skills` + "`" + `.` + "`" + `deleted` + "`" + `
FROM ` + "`" + `skills` + "`" + `
INNER JOIN ` + "`" + `skills_history` + "`" + ` ON ` + "`" + `skills` + "`" + `.` + "`" + `latest_history_id` + "`" + ` = ` + "`" + `skills_history` + "`" + `.` + "`" + `history_id` + "`" + `
`

type GetCurrentSkillsRow struct {
	HistoryID         int32
	PreviousHistoryID sql.NullInt32
	SkillID           int32
	FileVersion       int32
	Update            string
	Constant          sql.NullString
	Name              sql.NullString
	Description       sql.NullString
	MaxLevel          sql.NullInt32
	SpCost            []byte
	CanSelectLevel    sql.NullBool
	AttackRange       []byte
	RequiredSkills    []byte
	JobRequiredSkills []byte
	SkillScale        []byte
	CreatedAt         sql.NullTime
	ApCost            []byte
	IsPassive         sql.NullBool
	CastFlags         []byte
	CastFixedDelay    []byte
	CastStatDelay     []byte
	SinglePostDelay   []byte
	GlobalPostDelay   []byte
	Deleted           bool
}

func (q *Queries) GetCurrentSkills(ctx context.Context) ([]GetCurrentSkillsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCurrentSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCurrentSkillsRow
	for rows.Next() {
		var i GetCurrentSkillsRow
		if err := rows.Scan(
			&i.HistoryID,
			&i.PreviousHistoryID,
			&i.SkillID,
			&i.FileVersion,
			&i.Update,
			&i.Constant,
			&i.Name,
			&i.Description,
			&i.MaxLevel,
			&i.SpCost,
			&i.CanSelectLevel,
			&i.AttackRange,
			&i.RequiredSkills,
			&i.JobRequiredSkills,
			&i.SkillScale,
			&i.CreatedAt,
			&i.ApCost,
			&i.IsPassive,
			&i.CastFlags,
			&i.CastFixedDelay,
			&i.CastStatDelay,
			&i.SinglePostDelay,
			&i.GlobalPostDelay,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkillJobs = `-- name: GetSkillJobs :many
SELECT skills_jobs.constant, skills_jobs.job_id, skills_jobs.inherited_job, skills_jobs.inherited_job2, skills_jobs.first_update, skills_jobs.last_update, skills_jobs.deleted, skills_jobs.updated_at, skills_jobs.created_at FROM ` + "`" + `skills_jobs` + "`" + `
`

func (q *Queries) GetSkillJobs(ctx context.Context) ([]SkillsJob, error) {
	rows, err := q.db.QueryContext(ctx, getSkillJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillsJob
	for rows.Next() {
		var i SkillsJob
		if err := rows.Scan(
			&i.Constant,
			&i.JobID,
			&i.InheritedJob,
			&i.InheritedJob2,
			&i.FirstUpdate,
			&i.LastUpdate,
			&i.Deleted,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkillList = `-- name: GetSkillList :many
SELECT ` + "`" + `skills_history` + "`" + `.` + "`" + `skill_id` + "`" + `, ` + "`" + `skills_history` + "`" + `.` + "`" + `name` + "`" + `, ` + "`" + `skills_history` + "`" + `.` + "`" + `constant` + "`" + `, ` + "`" + `skills_history` + "`" + `.` + "`" + `update` + "`" + ` lastUpdate
FROM ` + "`" + `skills` + "`" + `
INNER JOIN ` + "`" + `skills_history` + "`" + ` ON ` + "`" + `skills_history` + "`" + `.` + "`" + `history_id` + "`" + ` = ` + "`" + `skills` + "`" + `.` + "`" + `latest_history_id` + "`" + `
WHERE ` + "`" + `skills` + "`" + `.` + "`" + `deleted` + "`" + ` = FALSE
ORDER BY ` + "`" + `skills_history` + "`" + `.` + "`" + `skill_id` + "`" + ` ASC
LIMIT ?, ?
`

type GetSkillListParams struct {
	Offset int32
	Limit  int32
}

type GetSkillListRow struct {
	SkillID    int32
	Name       sql.NullString
	Constant   sql.NullString
	Lastupdate string
}

func (q *Queries) GetSkillList(ctx context.Context, arg GetSkillListParams) ([]GetSkillListRow, error) {
	rows, err := q.db.QueryContext(ctx, getSkillList, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSkillListRow
	for rows.Next() {
		var i GetSkillListRow
		if err := rows.Scan(
			&i.SkillID,
			&i.Name,
			&i.Constant,
			&i.Lastupdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkillsIdsInUpdate = `-- name: GetSkillsIdsInUpdate :many
SELECT ` + "`" + `skills_history` + "`" + `.` + "`" + `history_id` + "`" + `, ` + "`" + `skills_history` + "`" + `.` + "`" + `skill_id` + "`" + `
FROM ` + "`" + `skills_history` + "`" + `
WHERE ` + "`" + `skills_history` + "`" + `.` + "`" + `update` + "`" + ` = ?
`

type GetSkillsIdsInUpdateRow struct {
	HistoryID int32
	SkillID   int32
}

func (q *Queries) GetSkillsIdsInUpdate(ctx context.Context, update string) ([]GetSkillsIdsInUpdateRow, error) {
	rows, err := q.db.QueryContext(ctx, getSkillsIdsInUpdate, update)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSkillsIdsInUpdateRow
	for rows.Next() {
		var i GetSkillsIdsInUpdateRow
		if err := rows.Scan(&i.HistoryID, &i.SkillID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
